from functools import lru_cache
from pathlib import Path
from urllib.parse import quote_plus

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    telegram_api_id: int | None = None
    telegram_api_hash: str | None = None
    telegram_phone: str | None = None
    telegram_session_path: Path = Path("backend/data/telegram_parser")
    parser_db_host: str = "localhost"
    parser_db_port: int = 5432
    parser_db_name: str = "brandradar"
    parser_db_user: str = "brandradar"
    parser_db_password: str = "brandradar"
    clickhouse_host: str = "localhost"
    clickhouse_port: int = 8123
    clickhouse_database: str = "brandradar_ml"
    clickhouse_user: str = "brandradar"
    clickhouse_password: str = "brandradar"
    api_title: str = "Telegram Parser API"
    api_version: str = "0.1.0"
    backend_cors_origins: str = "http://localhost:3000,http://127.0.0.1:3000"

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )# This file is auto-generated by DevPlatform for further customizing as you wish.
# NOTE: You should not delete this file!

stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - echo 'ok'

    @property
    def credentials_configured(self) -> bool:
        return bool(self.telegram_api_id and self.telegram_api_hash)

    @property
    def cors_origins(self) -> list[str]:
        return [
            item.strip()
            for item in self.backend_cors_origins.split(",")
            if item.strip()
        ]

    @property
    def parser_database_url(self) -> str:
        user = quote_plus(self.parser_db_user)
        password = quote_plus(self.parser_db_password)
        return (
            f"postgresql://{user}:{password}@{self.parser_db_host}:"
            f"{self.parser_db_port}/{self.parser_db_name}"
        )


@lru_cache
def get_settings() -> Settings:
    settings = Settings()
    settings.telegram_session_path.parent.mkdir(parents=True, exist_ok=True)
    return settings
